<html>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1"/>
      <link rel="stylesheet" href="css/bootstrap.css">
    	<link rel="stylesheet" href="css/slider.css">
  </head>

  <body>

		<!-- INICIO DO SLIDER -->
    <div>
      <section class="slider">
  			<div class="slider_box">
  				<article class="slider_item active"  slider-bg="img/slide1.jpg">
  				</article>

  				<article class="slider_item" slider-bg="img/slide2.jpg">

  				</article>

  				<article class="slider_item" slider-bg="img/slide3.jpg">

  				</article>

          <article class="slider_item" slider-bg="img/slide4.jpg">

  				</article>
  			</div>
  		</section>
    </div>
    <br>

    <section class="slice" id="contato">
    <div class="iframe">

        <div class="row">
            <div >
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1169.4626064781157!2d-52.66642436346594!3d-27.092619861526636!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94e4b5042043ed9b%3A0x11b002b8085f6b29!2sUniversidade+Comunit%C3%A1ria+Regional+de+Chapec%C3%B3+-+BLOCO+G+-+Av.+Ernesto+Jos%C3%A9+de+Marco+-+Efapi%2C+Chapec%C3%B3+-+SC!5e0!3m2!1spt-BR!2sbr!4v1492711001236" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>

            <form method="post"  role="form">
                   <div class="col-sm-4">
                       <div class="form-group">
                           <label for="name">Nome</label>
                           <input type="text" class="form-control" required name="name" id="name" placeholder="Nome" title="Digite seu nome" >
                       </div>
                       <div class="form-group">
                           <label for="email">Email</label>
                           <input type="email" class="form-control" required name="email" id="email" placeholder="E-mail" title="Por favor insira um endereço de e-mail ">
                       </div>
                   </div>
                   <div class="col-sm-4">
                       <div class="form-group">
                           <label for="comments"> Mensagem</label>
                           <textarea name="comment"  required class="form-control" id="comments" cols="3" rows="5" placeholder="Digite a sua Mensagem" title="Digite sua mensagem (pelo menos 10 caracteres)"></textarea>
                       </div>
                   </div>
                   <div class="col-md-8 col-md-offset-4">
                       <div class="result"></div>
                       <button name="submit" type="submit" class="btn btn-lg" id="submit"> Enviar</button>
                   </div>
               </form>

           </div>
       </div>

   </section>
    <script src="js/jquery-2.0.2.min.js"></script>
    <script src="js/slider.js"></script>
  </body>
</html>
