<?php

$title = 'Deletar Usuário';

$this->headTitle($title);
$url = $this->url('user', ['action' => 'delete', 'id' => $id]);

?>

<h1><?=$this->escapeHtml($title)?></h1>

<form action="<?php echo $url; ?>" method="post">
  <p>Tem certeza que quer deletar este usuário?</p>
  <div class="form-group">
    <input type="hidden" name="id" value="<?php echo $user->getId(); ?>">
    <input type="submit" class="btn btn-primary" name="del" value="Sim">
    <input type="submit" class="btn btn-default" name="No" value="Não">
  </div>

</form>
